hercules-ci/hercules-ci-effects

- effects/nixops/run-nixops.nix
Hmm, the effect jobs seem to be queued forever :thinking: 
Some integration tests on qemue have been running for a couple of days, could that be related?
> Add dry-run flag

- docs/modules/ROOT/pages/reference/nix-functions/runArion.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runNixDarwin.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runNixOS.adoc
- effects/arion/run-arion.nix
- effects/nix-darwin/run-nix-darwin.nix
- effects/nixos/run-nixos.nix
> Expose configs

- docs/modules/ROOT/examples/nix-shell.nix
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/nix-functions/nix-shell.adoc
- effects/default.nix
- effects/nix-shell/default.nix
- effects/nix-shell/test.nix
- flake.nix
> Add nix-shell function

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runCachixDeploy.adoc
- effects/cachix-deploy/run-cachix-deploy.nix
- effects/cachix-deploy/test.nix
- effects/default.nix
- flake.nix
> `runCachixDeploy` is a convenience function to invoke `cachix deploy activate`.
cc @Mic92 @domenkozar
> Add cachix deploy

- effects/default.nix
> runIf: Use inputDerivation in dependencies attr

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/nix-functions/netlifyDeploy.adoc
- effects/default.nix
- effects/netlify/default.nix
- effects/netlify/test/default.nix
- flake.nix
Hi @Kranzes, I've added tests and docs, and made some small changes.
Does this look ok to you?
> `netlifyDeploy` based on Kranzes' PR

- effects/nixos/run-nixos.nix
- effects/nixos/test.nix
- flake.nix
> `runNixOS`: do not pass `config` to `mkEffect`

- effects/netlify/default.nix
- flake.nix
Thanks @Kranzes for discovering and reporting.
> Fix `netlifyDeploy` cmdline leak

- docs/modules/ROOT/pages/guide/deploy-a-nixos-machine.adoc
https://search.nixos.org/options?channel=22.05&show=users.users.%3Cname%3E.openssh.authorizedKeys.keys&from=0&size=50&sort=relevance&type=packages&query=users.users.%3Cname%3E.openssh
> `.keyFiles` should be `.keys`

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/flake-parts/flake-update.adoc
- docs/modules/ROOT/pages/reference/nix-functions/flakeUpdate.adoc
Catching up to the standard.
Can't recommend such a short function doc, but I consider `flakeUpdate` to be more of an internal-ish thing for now.
> docs: Add flake-update, flakeUpdate

- effects/flake-update/flake-module.nix
- flake-modules/herculesCI-attribute.nix
- flake-modules/types/when.nix
> flake-modules/herculesCI-attribute: Make `when` a submodule

- effects/flake-update/default.nix
- effects/flake-update/flake-module.nix
- effects/flake-update/github-auto-merge.nix
> flake-update: Add auto-merge on GitHub

- flake-dev.nix
- flake-modules/herculesCI-eval-test.nix
- flake-modules/types/when.nix
Hi, and thank you for suggesting a contribution!
The following is my own checklist. If you can tick all boxes, great! If not, I might be able to help.
Please don't remove any items, but leave them unchecked, even if they don't apply.
> flakeModule: Fix dayOfWeek type

- effects/modules/git-auth.nix
> tidy: Remove a set -x

- effects/flake-update/effect-fun.nix
Fix
- Time for an effect test with github?
> flake-updater: Fix autoMergeMethod

- docs/modules/ROOT/pages/reference/nix-functions/flakeUpdate.adoc
> docs/flakeUpdate: Add example

- effects/effect/effect-module.nix
- flake-modules/github-pages.nix
> Git write branch

- flake-modules/herculesCI-attribute.nix
- flake-modules/herculesCI-eval-test.nix
- lib/mkHerculesCI-test.nix
- lib/testSupport.nix
Return `null` instead of throwing, as documented.
- n/a
> Fix `herculesCI.repo` nullable attrs

- effects/effect/effect.nix
- effects/modules/git-auth-gh.nix
- flake-modules/github-pages.nix
Make a few small improvements.
- self-documenting
- not worth the cost
- n/a
> Improvements

- vendor/hercules-ci-agent/default-herculesCI-for-flake.nix
Added
- formatter
Improved
- templates check
- darwinConfigurations ciSystems filtering
> vendor: Update

- docs/modules/ROOT/pages/reference/nix-functions/runNixDarwin.adoc
- effects/nix-darwin/eval-test.nix
- effects/nix-darwin/run-nix-darwin.nix
- effects/nix-darwin/test/configuration.nix
> `runNixDarwin`: support specifying pkgs

- flake-dev.nix
- flake-module.nix
- flake-modules/github-releases.nix
- flake-modules/github-releases/default.nix
- flake-modules/github-releases/effect.py
- flake-modules/github-releases/test/default.nix
- flake-modules/github-releases/test/fake-gh.py
- flake-modules/github-releases/test/fake-zip.py
Easy way to create GH Releases on tags.
> Add github-releases module

- effects/default.nix
- effects/effect/effect.nix
- effects/lib-version-check.nix
- flake-modules/module-argument.nix
Make sure we're not loaded with a version that's very old.
> Add lower bound to nixpkgs version

- effects/default.nix
- effects/effect/effect.nix
- effects/lib-version-check.nix
- flake-modules/module-argument.nix
This should help with troubleshooting, by making the means of invocation explicit.
> Add more precise component to version bound error

- effects/flake-update/effect-fun.nix
- effects/flake-update/flake-module.nix
Customize the flake-update effect arbitrarily using the module system.
> flake-update: Allow arbitrary extension of the effect

- effects/modules/git-update.nix
- effects/modules/git-update/test.nix
- flake-dev.nix
Catch a mistake.
Not committing for the user, because it'd have a bad commit message, and it the uncommitted files may have a different cause.
> git.update.script: Check that all changes are committed

- effects/modules.nix
- flake-dev.nix
- flake-public-outputs.nix
> Fix modules and add basic test

- docs/modules/ROOT/pages/reference/nix-functions/runCachixDeploy.adoc
> doc/runCachixDeploy: async must be true when deploying self

- effects/effect/effect-module.nix
> modularEffect: Set default empty env

- docs/modules/ROOT/pages/reference/nix-functions/runArion.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runNixDarwin.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runNixOS.adoc
- effects/nix-darwin/eval-test.nix
- effects/nix-darwin/run-nix-darwin.nix
\+ a few docs fixups
Make the API more consistent.
- n/a
> Make runNixDarwin more like runNixOS

- effects/ssh/call-ssh.nix
and:
- log to stderr
- don't clobber $r
Help with troubleshooting if needed.
Apply good practices.
> ssh: Log fail script build

- effects/effect-vm-test/effects-module.nix
- effects/flake-update/effect-fun.nix
- effects/flake-update/flake-module.nix
- effects/flake-update/test-module-eval.nix
- effects/flake-update/test.nix
- flake-dev.nix
Experimental Nix CLI changed. Support the new syntax.
> Flake update nix 2.19

- flake-dev.nix
(chore) improve updater as used locally.
> maint: Enable base merge

- effects/flake-update/flake-module.nix
> flake-update: Add note for potential feature

- effects/flake-update/effect-fun.nix
Discern each flake in the log, when multiple flakes are configured.
> flake-update: Log flake directory

- effects/flake-update/effect-fun.nix
- effects/flake-update/test.nix
Solve https://hercules-ci.com/github/nix-community/neovim-nightly-overlay/jobs/3311/effects/effects.flake-update/log
> Fix flake update for nix config

- effects/nix-darwin/run-nix-darwin.nix
https://github.com/nix-darwin/nix-darwin/pull/1341
> runNixDarwin: add sudo activation
