hercules-ci/hercules-ci-effects

- default.nix
- docs/modules/ROOT/pages/guide/import-or-pin.adoc
- effects/default.nix
- nix/ci.nix
If you were using the old `flake-compat` result, you *could* call `nix/flake-compat.nix` directly, but I would recommend to follow the documented import methods instead.
> Turn default.nix into a simple interface

- effects/nix-darwin/run-nix-darwin.nix
`activate` does not set the profile link. This is the responsibility
of the `switch` command, that also evaluates, which we don't want
so we set the profile in the effect itself to complete it.
Fixes #38
> Issue 38 nix darwin switch not just activate

- effects/effect/effects-setup-hook.sh
They add a lot of noise and some suggest that things happen that do not occur, e.g. putStatePhase, which is often empty.
> Remove phase headers

- effects/nixops2/run-nixops2.nix
- effects/nixops2/test/default.nix
Prevent others from encountering https://github.com/NixOS/nixops/issues/1499
State can be reverted, but it's still a really bad bug if you find out too late.
> Disable runNixOps2 action argument because of nixops#1499

- effects/nixops/run-nixops.nix
Was technically possible with overrideAttrs, but that's annoying.
> runNixOps: Make check scripts easier to override

- effects/netlify/default.nix
Without this, new secretsMap(s) cannot be introduced to the function call
> netlifyDeploy: wrap secretsMap

- effects/netlify/default.nix
Prior to this commit, only one secretsMap could be passed into the mkEffect function call, meaning that postEffect scripts that want to use secrets via readSecretString could not.
> netlifyDeploy: allow additional secretsMap

- effects/netlify/default.nix
The default output of netlify-cli is useless and spams the terminal with animation, which is not useful for reading by human or machine.
a postEffect can now use the JSON output of netlifyDeploy by reading the file named 'out', analogous to a $out in a normal Nix derivation. This is a good placeholder until effects support real outputs.
> netlifyDeploy: use JSON output and store it in a file named `netlify-result.json` for use in postEffect

- effects/effect/effect.nix
runCommandNoCC was aliased to runCommand but has how been changed to a throw
> replace runCommandNoCC with runCommand

- docs/modules/ROOT/pages/reference/nix-functions/effectVMTest.adoc
- effects/effect-vm-test/default.nix
- effects/effect-vm-test/effects-module.nix
- effects/ssh/test.nix
- effects/testsupport/dns.nix
- flake.lock
- flake.nix
Blocked on https://github.com/NixOS/nixpkgs/pull/176557
> Use modular NixOS test framework

- effects/effect/effect.nix
- effects/netlify/default.nix
When building an impure `contents`, it might not be clear what's happening. `netlify deploy` can be slow.
> `netlifyDeploy`: log before deploy

- effects/default.nix
- effects/effect-vm-test/default.nix
- effects/effect-vm-test/effects-module.nix
- effects/flake-update/default.nix
- effects/flake-update/flake-module.nix
- effects/flake-update/test.nix
- flake-dev.nix
- flake-module.nix
- flake-modules/derivationTree-type.nix
- flake-modules/herculesCI-attribute.nix
- flake-modules/herculesCI-helpers.nix
- flake-modules/module-argument.nix
- flake-public-outputs.nix
- flake.lock
- flake.nix
- vendor/hercules-ci-agent/default-herculesCI-for-flake.nix
- Stripped down, cleaned up version of https://github.com/hercules-ci/hercules-ci-effects/pull/85
- `herculesCI.onPush` etc attributes
- flake.parts module
- needs upcoming agent release and backend update (so doesn't run on hercules-ci.com yet)
- relies on deleting the `flake-update` branch a lot now. Can be improved later.
```
imports = [
inputs.hercules-ci-effects.flakeModule
];
flake-update.enable = true;
```
> Flake updater and defining `herculesCI.on*` jobs with options

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/guide/deploy-to-github-pages.adoc
- docs/modules/ROOT/pages/guide/import-or-pin.adoc
- docs/modules/ROOT/pages/reference/effect-modules/core.adoc
- docs/modules/ROOT/pages/reference/effect-modules/git.adoc
- docs/modules/ROOT/pages/reference/flake-parts/github-pages.adoc
- docs/modules/ROOT/pages/reference/nix-functions/gitWriteBranch.adoc
- effects/default.nix
- effects/effect-vm-test/effects-module.nix
- effects/flake-update/test.nix
- effects/modules/git-update.nix
- effects/testsupport/gitea.nix
- effects/testsupport/setup.nix
- effects/write-branch/effect-module.nix
- effects/write-branch/test.nix
- flake-dev.nix
- flake-docs-render.nix
- flake-module.nix
- flake-modules/github-pages.nix
- flake-modules/herculesCI-attribute.nix
- flake-public-outputs.nix
- lib/mkHerculesCI-test.nix
- lib/mkHerculesCI.nix
- options.xsl
Support more git operations.
- Reusable git setup code in the form of documented modules
- `gitWriteBranch` effect
- GitHub pages module for flake-parts
TODO:
> `gitWriteBranch` and more

- docs/modules/ROOT/pages/reference/nix-functions/runNixDarwin.adoc
- effects/nix-darwin/eval-test.nix
- effects/nix-darwin/run-nix-darwin.nix
- effects/nix-darwin/test/configuration.nix
- flake-dev.nix
Make `runNixDarwin` work with pre-evaluated configurations, such as in flakes.
- n/a
> nix-darwin: Allow `darwinSystem` result or `config` to be passed.

- default.nix
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/guide/import-or-pin.adoc
- docs/modules/ROOT/pages/reference/effect-modules.adoc
- docs/modules/ROOT/pages/reference/effect-modules/git.adoc
- docs/modules/ROOT/pages/reference/nix-functions/modularEffect.adoc
- effects/default.nix
- effects/modules.nix
- flake-public-outputs.nix
Expose the `modularEffect` modules properly with attributes.
Use the `hci-effects` name consistently and improve docs.
- manually tested the entrypoints
> Expose effect modules, use `hci-effects` name instead of just `effects`

- effects/flake-update/effect-fun.nix
- effects/flake-update/flake-module.nix
- effects/flake-update/test.nix
- effects/modules/git-update.nix
Keep the update branch up to date.
If the CI fails on the update branch, we want to automatically pull from the main branch, as it may contain fixes.
This behavior is not enabled by default yet. Use e.g.
```nix
hercules-ci.flake-update.baseMerge.enable = true;
```
- will be default behavior, so no guide needed
> git-update / flake-update: keep branch up to date with `baseMerge`

- docs/modules/ROOT/pages/reference/nix-functions/runNixDarwin.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runNixOS.adoc
- docs/modules/ROOT/pages/reference/nix-functions/ssh.adoc
- effects/nix-darwin/eval-test.nix
- effects/nix-darwin/run-nix-darwin.nix
- effects/nixos/eval-test.nix
- effects/nixos/run-nixos.nix
- effects/nixos/test/configuration.nix
- effects/nixos/test/hardware-configuration.nix
- effects/ssh/call-ssh.nix
- effects/ssh/test.nix
- flake-dev.nix
- lib/testSupport.nix
- Allow realisation to happen on the destination instead.
Useful for bootstrapping an agent with the `hci` command.
- Modernize `runNixOS` a bit
- Docs improvements
- n/a
> ssh/NixOS/nix-darwin: add `ssh.buildOnDestination`

- flake-dev.nix
- flake.lock
- flake.nix
It's not needed at this time.
Flake lock file updates:
• Removed input 'hercules-ci-agent'
• Removed input 'hercules-ci-agent/flake-parts'
• Removed input 'hercules-ci-agent/flake-parts/nixpkgs-lib' • Removed input 'hercules-ci-agent/haskell-flake'
• Removed input 'hercules-ci-agent/nixpkgs'
Tidy up.
Alleviates #150.
> flake.nix: Remove hercules-ci-agent dependency (chore)

- flake.lock
- flake.nix
Flake lock file updates:
• Updated input 'flake-parts/nixpkgs-lib':
'github:NixOS/nixpkgs/f5892ddac112a1e9b3612c39af1b72987ee5783a?dir=lib' (2023-09-29)
→ follows 'nixpkgs'
Fixes #150
> flake.nix: Follow for flake-parts/nixpkgs-lib (chore)

- docs/modules/ROOT/pages/reference/nix-functions/runNixDarwin.adoc
- docs/modules/ROOT/pages/reference/nix-functions/runNixOS.adoc
- effects/modules/git-update.nix
- effects/modules/git-update/test.nix
Make `git.update.baseMerge.method = "rebase"` work in non-trivial cases.
- n/a
- n/a
> git-update: allow force push after rebase, safely

- vendor/hercules-ci-agent/default-herculesCI-for-flake.nix
Fixes ciSystems filtering for nix-darwin.
See https://github.com/hercules-ci/hercules-ci-agent/pull/578
> maint: Update default-herculesCI-for-flake.nix

- effects/effect/effect-module.nix
- effects/effect/test/dev-kvm.nix
- flake-dev.nix
Make use of `__hci_effect_mounts` convenient - mount any path into the effect, [as permitted](https://docs.hercules-ci.com/hercules-ci-agent/agent-config#effectMountables) by the agent.
> feat: Add mounts option to modularEffect

- effects/write-branch/effect-module.nix
- effects/write-branch/test.nix
> fix: Always mkdir -p $parent in gitWriteBranch

- effects/effect/effect-module.nix
- effects/effect/test/uid.nix
- flake-dev.nix
Some applications simply don't like to be UID 0, even if it's harmless.
Specifying `__hci_effect_*` by hand isn't very nice.
- now it is
> Add uid and gid in modularEffect

- effects/nix-darwin/run-nix-darwin.nix
fixes this warning:
warning: $HOME ('/Users/customer') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
matches the sudo command used in nix-darwin:
https://github.com/LnL7/nix-darwin/blob/87131f51f8256952d1a306b5521cedc2dc61aa08/pkgs/nix-tools/darwin-rebuild.sh#L27
> runNixDarwin: add `-H` to sudo

- effects/effect/effect-module.nix
- effects/effect/effect.nix
- effects/effect/effects-setup-hook.sh
- effects/effect/test/setup.nix
- effects/effect/test/uid.nix
- flake-dev.nix
Provide `/bin/sh` and `/usr/bin/env`, because some programs rely on those.
We can do so in a pure way.
- N/A Is the corresponding module up to date?
> Add `/bin/sh` and other fs root things
